### ISSUE TITLE
Add ability to add query parameters to javascript call

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce-paypal-checkout#14]
It would be great to have the ability to add url parameters from config for customizing features

https://developer.paypal.com/docs/checkout/reference/customize-sdk/#query-parameters

I would like to add this parameter

&disable-funding=credit,card

So ideally if it can be generic so we can add any set of url parameters as necessary. This would take care of the query parameter in #12 for example.

Thanks!

**Comment by nfourtythree** [comment]
Hi @keyurshah 

We have added the ability to pass `disable-funding` and/or `disable-card` in the form parameters.

```
{{ cart.gateway.getPaymentFormHtml({ 'disable-funding': 'credit,card' }) }}
```

Because of the nature of something things we need to control we haven't just opened up the query string but have added allowed params.

Hope this helps! This will be included in the next release.

**Comment by keyurshah** [comment]
That is great! Thank you so much
