### ISSUE TITLE
Error: Expected an order id to be passed (again)

### ISSUE THREAD

**Issue by sjelfull** [craftcms/commerce-paypal-checkout#16]
```json
{"name":"INVALID_REQUEST","message":"Request is not well-formed, syntactically incorrect, or violates schema.","debug_id":"c189692123250","details":[{"location":"body","issue":"INVALID_SYNTAX","description":"Cannot deserialize instance of `java.lang.String` out of START_OBJECT token line: 1, column: 303"}],"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_SYNTAX","rel":"information_link","encType":"application/json"}]}
```

Settings seems fine - test mode is enabled:
![image](https://user-images.githubusercontent.com/10508/81937057-5ee6d880-95f3-11ea-9cdd-3fd6d237645e.png)

**Comment by nfourtythree** [comment]
Hi @sjelfull 

I am unable to replicate this issue. Could you please provide more information.

What did the cart look like? Products, shipping, adjustments etc.

Thanks.

**Comment by giorgiopogliani** [comment]
Hi @nfourtythree,
 
I have the same issue, too. 

I'm in test mode and trying to complete the checkout with a [digital product](https://github.com/craftcms/digital-products). I didn't set the shipping because there is no shipping, I'm not sure if I have to specify a "no shipping" settings. The user is registered and activated.

**Comment by giorgiopogliani** [comment]
One more thing if can help, the alert says "SyntaxError: Unexpected token T in JSON at position 0" but in the browser console I see the error "Expected an order id to be passed"

**Comment by giorgiopogliani** [comment]
In the admin panel, under the transactions tab I see all the failed payments with this message: 

<img width="615" alt="image" src="https://user-images.githubusercontent.com/28866565/88802368-44aca780-d1ab-11ea-90eb-c048cbbbcfa6.png">

**Comment by nfourtythree** [comment]
Closing this issue due to no further information.

Thanks.

**Comment by orosznyet** [comment]
I've tested the flow with test creds and everything was good but then I've tried the live credentials (the gateway was still in test mode) and I've got the aforementioned alert too when I clicked the PayPal button. 

![image](https://user-images.githubusercontent.com/577015/109515079-f942da80-7aa6-11eb-8663-d4c1aaff478e.png)

Investigating the network request I found this:
```
POST /index.php?p=actions/commerce/payments/pay
cart: {number: "d1c7cd18c8c00b559e9b74ac33ccbd0a", reference: null, couponCode: null, isCompleted: false,…}
error: "{"error":"invalid_client","error_description":"Client Authentication failed"}"
paymentFormErrors: []
```

So the alert was right I guess but the actual error was something else. Having a better a error message would help devs to debug this issue faster because the current error is misleading.

**Comment by nfourtythree** [comment]
Hi

As @orosznyet mentioned it seems like this issue is coming from a situation where the wrong credentials are being used (live credentials but with test mode enabled) or an issue with the PayPal account.

@rob-baker-ar if the payments controller pay action is using the wrong gateway that would seem to suggest an issue elsewhere with your code rather than the PayPal plugin. It would be worth checking to see which gateway is being passed/which is set on the cart.

Thanks.

**Comment by rob-baker-ar** [comment]
Sorry, should have updated this. My issue with PayPal disappeared when I ditched the older PayPal integration plugin in favour of the new. Some templates were looking at the gateway handle to decide what to do / show, which stayed the same during the transfer between plugins, hence the confusion. I resolved it in the end by removing all the PayPal specific gateway / payment stage of checkout customisations that it turned out were not needed with the new gateway implementation anyway.
