### ISSUE TITLE
Emails from PayPal regarding PayPal Instant Payment Notifications

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce-paypal-checkout#18]
My client has been a number of emails from Paypal stating the following. 

```
Please check your server that handles PayPal Instant Payment Notifications (IPN). Instant Payment Notifications sent to the following URL(s) are failing:

https://www.xxxxxxxxx.com/paypal/ipn/
https://www.xxxxxxxxx.com/checkout/paypal_ipn

If you do not recognize this URL, you may be using a service provider that is using IPN on your behalf. Please contact your service provider with the above information. If this problem continues, IPNs may be disabled for your account.
```

I am not too sure what they mean, is this something that is being caused by your plugin?

**Comment by nfourtythree** [comment]
Hi @iamtompickering 

This plugin does not utilise PayPal's IPN service. My assumption here is that the client has this turned on in their account.

If this is the only selling portal that the client uses for taking PayPal payments then you should be safe to disable IPN. Otherwise, you may need to update the address to the correct URL for the integration they are using IPN on.

Thanks.
