### ISSUE TITLE
Configure PayPal payment options

### ISSUE THREAD

**Issue by keyurshah** [craftcms/commerce-paypal-checkout#5]
What would be the best way to remove payment options in the form?

Ideally I just would like the yellow PayPal button.

We are offering PayPal in conjunction with Authorize.net and don't need the PayPal Credit and Visa / MasterCard options through Paypal.  Thanks.

![image](https://user-images.githubusercontent.com/744385/68516720-a736cf80-0239-11ea-8757-55d428b216c8.png)

**Comment by nfourtythree** [comment]
Hi @keyurshah 

For the moment we are rolling with the default setup for the moment with looking at how we can improve this in the future.

You can, of course, roll your own implementation of the JS.

To do this you can get the example markup output from the [payment form template](https://github.com/craftcms/commerce-paypal-checkout/blob/develop/src/templates/paymentForm.html) and the JS from the [payment form javascript](https://github.com/craftcms/commerce-paypal-checkout/blob/develop/src/resources/js/paymentForm.js).

With those, you can put them directly into your own template instead of using `{{ cart.gateway.getPaymentFormHtml({})|raw }}`. This way you can customise it with exactly what you need.

In the PayPal docs, it explains the different options available to you for [customising the buttons](https://developer.paypal.com/docs/checkout/integration-features/customize-button/) and even [disabling funding methods](https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-funding).

There are so many options in the implementation that it would be a struggle to offer options to cover every single one. If it turns out there are some common options that lots of people using we can look to add them, however, for the moment it would be best to take the implementation root outlined above.

Hope this helps!

**Comment by keyurshah** [comment]
That sounds good, I can try to customize the form. Agree, it would be difficult to cover all the options for everyone.
