### ISSUE TITLE
impossible to make a paypal payment manually from amdin

### ISSUE THREAD

**Issue by CaporalJuju** [craftcms/commerce-paypal-checkout#84]
the paypal method does not appear in the backend choices.
but it is functional in the front end for users.

![Screenshot 2024-03-04 at 3 23 00 PM](https://github.com/craftcms/commerce-paypal-checkout/assets/34747138/0aba4819-b068-4979-9075-6317d1db60b3)

**Comment by nfourtythree** [comment]
Hi @CaporalJuju 

Thank you for your message, due to the nature of PayPal and the implementation of this plugin there is no control panel functionality for taking a payment.

You would need to take the payment via [PayPal's virtual terminal](https://www.paypal.com/uk/cshelp/article/whats-virtual-terminal-and-how-does-it-work-help195) in your account and then add a [manual payment](https://craftcms.com/docs/commerce/4.x/payment-gateways.html#manual-gateway) to the order.

We are looking to improve the integration in the virtual to see if there is anything ewe can do to make a link between the PayPal virtual terminal and Commerce.

Thanks!
